# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)
ENV["FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD"] = "xsmj-rlzh-rvwp-vzcw"

platform :ios do
  
  desc "Push a new beta build to TestFlight"
  lane :beta do
    ensure_git_status_clean
    increment_build_number(
      build_number: latest_testflight_build_number + 1,
     xcodeproj: "MyTravel.xcodeproj"
    )
    commit_version_bump(xcodeproj: "MyTravel.xcodeproj")
    add_git_tag
    push_to_git_remote
    build_app(
      scheme: "MyTravel",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          "com.com.pedro.POC-Scanner" => "POC scanner App Store"
        }
      }
    )
    changelog_from_git_commits(
      merge_commit_filtering: 'exclude_merges'
    )
    upload_to_testflight(
        distribute_external: true,
        groups: 'External group1'
    )
  end

end
